name: Deploy Staging

on:
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: gd-gcp-gridu-devops-t1-t2
          service_account_key: ${{ secrets.GCLOUD_AUTH_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Authenticate Kubectl
        run: gcloud container clusters get-credentials malazarevic-staging --region us-central1 --project gd-gcp-gridu-devops-t1-t2

      - name: Apply Kubernetes Manifests (STAGING)
        run: |
          gcloud components install gke-gcloud-auth-plugin
          kubectl apply -f deploy/kubernetes/complete-demo.yaml